"""add tickets normalized_text

Revision ID: 4103ebb98256
Revises: 5792dfe4a836
Create Date: 2026-07-16 10:21:41.078961

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "4103ebb98256"
down_revision: Union[str, Sequence[str], None] = "5792dfe4a836"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tickets",
        sa.Column(
            "normalized_text",
            sa.Text(),
            nullable=False,
            comment="raw_text в нижнем регистре без пунктуации — для поиска дублей",
        ),
    )
    op.create_index(
        "ix_tickets_normalized_text", "tickets", ["normalized_text"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tickets_normalized_text", table_name="tickets")
    op.drop_column("tickets", "normalized_text")
    # ### end Alembic commands ###
