"""split tokens_used into prompt and completion tokens

Revision ID: d234ba37270d
Revises: 4103ebb98256
Create Date: 2026-07-16 11:48:13.264139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "d234ba37270d"
down_revision: Union[str, Sequence[str], None] = "4103ebb98256"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tickets",
        sa.Column(
            "prompt_tokens",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Токены на входе (промпт) — обычно дешевле выходных",
        ),
    )
    op.add_column(
        "tickets",
        sa.Column(
            "completion_tokens",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Токены на выходе (ответ модели) — обычно дороже входных",
        ),
    )
    op.drop_column("tickets", "tokens_used")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tickets",
        sa.Column(
            "tokens_used",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
            comment="Суммарное число токенов, потраченных на обработку",
        ),
    )
    op.drop_column("tickets", "completion_tokens")
    op.drop_column("tickets", "prompt_tokens")
    # ### end Alembic commands ###
